on:
  push:
    paths:
      - 'targets/apps/VAmPI-master/**'


jobs:
  run-scripts:
    runs-on: ubuntu-latest

    name: Horusec Scan
    steps:
      - uses: actions/checkout@v3
      - name: SAST - Horusec Run ðŸž
        run: |
          ls -R
          cd ./targets/apps/VAmPI-master ; curl -sL https://raw.githubusercontent.com/0xtiago/opensource-devsecops/main/tools/horusec/horusec_linux.sh| bash

      - name: SAST - Horusec Report Generation ðŸ“Š
        run: | 
          cd ./targets/apps/VAmPI-master/reports
          pip install -r https://raw.githubusercontent.com/0xtiago/opensource-devsecops/main/tools/horusec/horusec_json2md/requirements.txt
          curl -sL https://raw.githubusercontent.com/0xtiago/opensource-devsecops/main/tools/horusec/horusec_json2md/horusec_json2md.py  -o horusec_json2md.py 
          python3 horusec_json2md.py horusec_report.json horusec_report.md


      - name: SAST - Horusec Upload Report Artifact ðŸ’¾
        uses: actions/upload-artifact@v3
        with:
          name: SAST - Horusec Scan
          path: reports/horusec_report.md

      - name: SAST - Horusec Results In Summary ðŸ’ðŸ½
        run: cat ./targets/apps/VAmPI-master/reports/horusec_report.md >> $GITHUB_STEP_SUMMARY


      

      